"""Synapse Python & C-FFI Interoperability Bridge."""

from synapse.interop.python_bridge import PythonBridge, to_synapse_tensor, to_numpy
from synapse.interop.eco_bridge import TransparentPyResolver, PackageNotFoundError
from synapse.interop.auto_pip import AutoPipManager, FileLock
from synapse.interop.dlpack import (
    from_dlpack,
    to_dlpack,
    is_dlpack_available,
    DLDevice,
    DLDataType,
    DLTensor,
    DLManagedTensor,
    DLDeviceType,
    DLDataTypeCode,
)
from synapse.interop.cuda_cublas import CuBlasEngine
from synapse.interop.c_ffi import (
    CDynamicLibrary,
    CFunction,
    load_library,
    get_tensor_pointer,
    resolve_type,
    pointer_to,
    get_cublas_engine,
    SynapseFFIError,
    int8,
    int16,
    int32,
    int64,
    uint8,
    uint16,
    uint32,
    uint64,
    float32,
    float64,
    char_p,
    void_p,
    size_t,
    bool_t,
)
from synapse.interop.c_bind import (
    CBindManager,
    CHeaderParser,
    CFunctionPrototype,
    CParameter,
    CBoundFunction,
    CBindResult,
    CHeaderParseError,
    bind_header,
    parse_header,
    parse_prototype,
)

from synapse.interop.stubs import DynamicStubGenerator

__all__ = [
    "DynamicStubGenerator",
    "CBindManager",
    "CHeaderParser",
    "CFunctionPrototype",
    "CParameter",
    "CBoundFunction",
    "CBindResult",
    "CHeaderParseError",
    "bind_header",
    "parse_header",
    "parse_prototype",
    "AutoPipManager",
    "FileLock",
    "TransparentPyResolver",
    "PackageNotFoundError",
    "PythonBridge",
    "to_synapse_tensor",
    "to_numpy",
    "from_dlpack",
    "to_dlpack",
    "is_dlpack_available",
    "DLDevice",
    "DLDataType",
    "DLTensor",
    "DLManagedTensor",
    "DLDeviceType",
    "DLDataTypeCode",
    "CDynamicLibrary",
    "CFunction",
    "load_library",
    "get_tensor_pointer",
    "resolve_type",
    "pointer_to",
    "get_cublas_engine",
    "CuBlasEngine",
    "SynapseFFIError",
    "int8",
    "int16",
    "int32",
    "int64",
    "uint8",
    "uint16",
    "uint32",
    "uint64",
    "float32",
    "float64",
    "char_p",
    "void_p",
    "size_t",
    "bool_t",
]



