/* Generated by Synapse Ahead-Of-Time (AOT) C Transpiler */
/* High-Performance Hardware SIMD Optimization & Vectorization Hints */
/* Recommended Compiler Flags: -O3 -mavx2 -mfma -fopenmp */
#include <stdio.h>
#include <stdlib.h>
#include <stdbool.h>
#include <math.h>
#include "synapse_runtime.h"

/* High-Performance SIMD Vectorized Tensor Kernels (AVX2 / FMA / OpenMP SIMD) */
#if defined(_OPENMP)
#include <omp.h>
#endif

/* SIMD Kernel: Tensor Addition */
static inline void syn_simd_tensor_add(const double* restrict a, const double* restrict b, double* restrict out, int size) {
    #pragma omp simd
    for (int i = 0; i < size; i++) {
        out[i] = a[i] + b[i];
    }
}

/* SIMD Kernel: Tensor Element-Wise Multiplication */
static inline void syn_simd_tensor_mul(const double* restrict a, const double* restrict b, double* restrict out, int size) {
    #pragma omp simd
    for (int i = 0; i < size; i++) {
        out[i] = a[i] * b[i];
    }
}

/* SIMD Kernel: Matrix Multiplication (GEMM with FMA & Vectorization) */
static inline void syn_simd_tensor_matmul(const double* restrict a, const double* restrict b, double* restrict out, int m, int k, int n) {
    #pragma omp simd
    for (int i = 0; i < m; i++) {
        for (int j = 0; j < n; j++) {
            double sum = 0.0;
            #pragma omp simd reduction(+:sum)
            for (int p = 0; p < k; p++) {
                sum += a[i * k + p] * b[p * n + j];
            }
            out[i * n + j] = sum;
        }
    }
}

/* Function Prototypes */
double relu_activation(double x);
int quantize_feature(double val, double scale);
double dequantize_feature(int qval, double scale);
double compute_linear_neuron(double input_val, double weight, double bias);
int predict_anomaly(double score, double threshold);

/* Function Definitions */
#line 16 "examples/edge_wasm_inference/main.syn"
double relu_activation(double x) {
#line 17 "examples/edge_wasm_inference/main.syn"
        if ((x > 0.0)) {
#line 18 "examples/edge_wasm_inference/main.syn"
            return x;
        }
#line 19 "examples/edge_wasm_inference/main.syn"
        return 0.0;
}
#line 21 "examples/edge_wasm_inference/main.syn"
int quantize_feature(double val, double scale) {
#line 22 "examples/edge_wasm_inference/main.syn"
        double scaled = (val / scale);
#line 23 "examples/edge_wasm_inference/main.syn"
        if ((scaled > 127.0)) {
#line 24 "examples/edge_wasm_inference/main.syn"
            return 127;
        }
#line 25 "examples/edge_wasm_inference/main.syn"
        if ((scaled < (-128.0))) {
#line 26 "examples/edge_wasm_inference/main.syn"
            return (-128);
        }
#line 27 "examples/edge_wasm_inference/main.syn"
        return int(scaled);
}
#line 29 "examples/edge_wasm_inference/main.syn"
double dequantize_feature(int qval, double scale) {
#line 30 "examples/edge_wasm_inference/main.syn"
        return syn_mul_scalar(float(qval), scale);
}
#line 32 "examples/edge_wasm_inference/main.syn"
double compute_linear_neuron(double input_val, double weight, double bias) {
#line 33 "examples/edge_wasm_inference/main.syn"
        double raw_sum = ((input_val * weight) + bias);
#line 34 "examples/edge_wasm_inference/main.syn"
        return relu_activation(raw_sum);
}
#line 36 "examples/edge_wasm_inference/main.syn"
int predict_anomaly(double score, double threshold) {
#line 37 "examples/edge_wasm_inference/main.syn"
        if ((score >= threshold)) {
#line 38 "examples/edge_wasm_inference/main.syn"
            return 1;
        }
#line 39 "examples/edge_wasm_inference/main.syn"
        return 0;
}

int main(int argc, char** argv) {
#line 6 "examples/edge_wasm_inference/main.syn"
    printf("%s\n", "==================================================================");
#line 7 "examples/edge_wasm_inference/main.syn"
    printf("%s\n", "Synapse Edge WebAssembly (WASM) Client-Side Inference Engine");
#line 8 "examples/edge_wasm_inference/main.syn"
    printf("%s\n", "==================================================================");
#line 44 "examples/edge_wasm_inference/main.syn"
    printf("%s\n", "\n[Stage 1] Client-Side Tensor Matrix Multiplication & Activation...");
#line 47 "examples/edge_wasm_inference/main.syn"
    syn_tensor_t* X = syn_tensor_create((const double[]){1.200000, 0.000000, 0.800000, 1.400000}, (const int[]){2, 2}, 2, 0);
#line 50 "examples/edge_wasm_inference/main.syn"
    syn_tensor_t* W = syn_tensor_create((const double[]){0.750000, 0.000000, 0.500000, 0.900000}, (const int[]){2, 2}, 2, 0);
#line 53 "examples/edge_wasm_inference/main.syn"
    syn_tensor_t* Y = syn_matmul(X, W);
#line 54 "examples/edge_wasm_inference/main.syn"
    (printf("%s ", "Input Tensor X (2x2):"),
    syn_tensor_print("", X));
#line 55 "examples/edge_wasm_inference/main.syn"
    (printf("%s ", "Weight Tensor W (2x2):"),
    syn_tensor_print("", W));
#line 56 "examples/edge_wasm_inference/main.syn"
    (printf("%s ", "Forward Output Y = X @ W:"),
    syn_tensor_print("", Y));
#line 61 "examples/edge_wasm_inference/main.syn"
    printf("%s\n", "\n[Stage 2] Evaluating Edge INT8 Quantization Accuracy...");
#line 63 "examples/edge_wasm_inference/main.syn"
    double sample_val = 2.45;
#line 64 "examples/edge_wasm_inference/main.syn"
    double scale = 0.025;
#line 65 "examples/edge_wasm_inference/main.syn"
    int q_code = quantize_feature(sample_val, scale);
#line 66 "examples/edge_wasm_inference/main.syn"
    double recovered_val = dequantize_feature(q_code, scale);
#line 68 "examples/edge_wasm_inference/main.syn"
    printf("%s %.6f\n", "Float32 Feature Value :", (double)(sample_val));
#line 69 "examples/edge_wasm_inference/main.syn"
    printf("%s %d\n", "INT8 Quantized Code   :", q_code);
#line 70 "examples/edge_wasm_inference/main.syn"
    printf("%s %.6f\n", "Dequantized Feature   :", (double)(recovered_val));
#line 73 "examples/edge_wasm_inference/main.syn"
    double neuron_output = compute_linear_neuron(sample_val, 0.85, (-0.4));
#line 74 "examples/edge_wasm_inference/main.syn"
    int anomaly_detected = predict_anomaly(neuron_output, 1.0);
#line 76 "examples/edge_wasm_inference/main.syn"
    printf("%s %.6f\n", "Linear + ReLU Activation:", (double)(neuron_output));
#line 77 "examples/edge_wasm_inference/main.syn"
    printf("%s %d\n", "Anomaly Decision Flag   :", anomaly_detected);
#line 82 "examples/edge_wasm_inference/main.syn"
    printf("%s\n", "\n[Stage 3] Single-Threaded Browser Request Queue Simulation...");
#line 86 "examples/edge_wasm_inference/main.syn"
    int task_queue = 0;
#line 93 "examples/edge_wasm_inference/main.syn"
    int completed_tasks = 0;
#line 94 "examples/edge_wasm_inference/main.syn"
    int idx = 0;
#line 95 "examples/edge_wasm_inference/main.syn"
    while ((idx < len(task_queue))) {
#line 96 "examples/edge_wasm_inference/main.syn"
        double t = task_queue[(int)(idx)];
#line 97 "examples/edge_wasm_inference/main.syn"
        double out = compute_linear_neuron(t[(int)("val")], t[(int)("w")], t[(int)("b")]);
#line 98 "examples/edge_wasm_inference/main.syn"
        int flag = predict_anomaly(out, 1.2);
#line 99 "examples/edge_wasm_inference/main.syn"
        (completed_tasks->append)(0);
#line 104 "examples/edge_wasm_inference/main.syn"
        idx += 1;
    }
#line 106 "examples/edge_wasm_inference/main.syn"
    (printf("%s ", "Single-Threaded Queue Processed:"),
    syn_tensor_print("", len(completed_tasks)),
    printf("%s\n", "edge inference requests:"));
#line 107 "examples/edge_wasm_inference/main.syn"
    int p = 0;
#line 108 "examples/edge_wasm_inference/main.syn"
    while ((p < len(completed_tasks))) {
#line 109 "examples/edge_wasm_inference/main.syn"
        double item = completed_tasks[(int)(p)];
#line 110 "examples/edge_wasm_inference/main.syn"
        syn_tensor_print("", syn_add(syn_add(syn_add_scalar(str(item[(int)("activation")]), (("  * [" + item[(int)("task_id")]) + "] Output: ")), " -> Alert: "), str(item[(int)("is_anomaly")])));
#line 111 "examples/edge_wasm_inference/main.syn"
        p += 1;
    }
#line 113 "examples/edge_wasm_inference/main.syn"
    printf("%s\n", "\n==================================================================");
#line 114 "examples/edge_wasm_inference/main.syn"
    printf("%s\n", "Edge WebAssembly Inference Module Verified Successfully!");
#line 115 "examples/edge_wasm_inference/main.syn"
    printf("%s\n", "Compile to WASM with: synapse build main.syn --target=wasm --html");
#line 116 "examples/edge_wasm_inference/main.syn"
    printf("%s\n", "==================================================================");
    return 0;
}
