"""
Synapse Python C-Extension Emitter.
Transpiles Synapse functions into a fully compliant CPython C-Extension (.c)
that compiles to native .pyd (Windows) or .so (Linux/macOS).
Allows Python developers to import Synapse modules at raw C speed:
    import my_synapse_module
"""
from __future__ import annotations
import os
import re
from typing import List, Optional
from synapse.parser.ast_nodes import Program, FunctionDef, Stmt, ReturnStmt
from synapse.codegen.c_emitter import CEmitter


class PyExtEmitter:
    def __init__(self, module_name: str = "synapse_ext"):
        self.module_name = re.sub(r"[^a-zA-Z0-9_]", "_", module_name)
        self.c_emitter = CEmitter()

    def emit(self, ast: Program) -> str:
        """Synapse AST'sindeki fonksiyonları CPython C-Uzantısı koduna dönüştürür."""
        # AST içindeki FunctionDef'leri ayıkla
        functions: List[FunctionDef] = [stmt for stmt in ast.statements if isinstance(stmt, FunctionDef)]

        # 1. C Fonksiyon Prototipleri ve Gövdeleri
        for fn in functions:
            fn_code = self.c_emitter.emit_function(fn)
            self.c_emitter.functions_code.append(fn_code)

        lines: List[str] = [
            "/* Generated by Synapse Python C-Extension Emitter */",
            "#define PY_SSIZE_T_CLEAN",
            "#include <Python.h>",
            "#include <stdio.h>",
            "#include <stdlib.h>",
            "#include <stdbool.h>",
            "#include <math.h>",
            '#include "synapse_runtime.h"',
            "",
            "/* ========================================================================= */",
            "/* C Function Prototypes                                                    */",
            "/* ========================================================================= */",
        ]
        lines.extend(self.c_emitter.prototypes)
        lines.append("")

        lines.append("/* ========================================================================= */")
        lines.append("/* C Function Implementations                                              */")
        lines.append("/* ========================================================================= */")
        lines.extend(self.c_emitter.functions_code)
        lines.append("")

        lines.append("/* ========================================================================= */")
        lines.append("/* CPython Wrapper Functions                                               */")
        lines.append("/* ========================================================================= */")

        method_entries: List[str] = []

        for fn in functions:
            wrapper_code, entry = self._emit_wrapper(fn)
            lines.append(wrapper_code)
            method_entries.append(entry)

        # Method Table
        lines.append("/* ========================================================================= */")
        lines.append("/* Module Method Table                                                      */")
        lines.append("/* ========================================================================= */")
        lines.append(f"static PyMethodDef {self.module_name}_methods[] = {{")
        for entry in method_entries:
            lines.append(f"    {entry},")
        lines.append("    {NULL, NULL, 0, NULL}")
        lines.append("};")
        lines.append("")

        # Module Definition & PyInit
        lines.append("/* ========================================================================= */")
        lines.append("/* Module Definition & Initialization                                       */")
        lines.append("/* ========================================================================= */")
        lines.append(f"static struct PyModuleDef {self.module_name}_module = {{")
        lines.append("    PyModuleDef_HEAD_INIT,")
        lines.append(f'    "{self.module_name}",')
        lines.append(f'    "Compiled Synapse Native Extension: {self.module_name}",')
        lines.append("    -1,")
        lines.append(f"    {self.module_name}_methods")
        lines.append("};")
        lines.append("")
        lines.append(f"PyMODINIT_FUNC PyInit_{self.module_name}(void) {{")
        lines.append(f"    return PyModule_Create(&{self.module_name}_module);")
        lines.append("}")
        lines.append("")

        return "\n".join(lines)

    def _emit_wrapper(self, fn: FunctionDef) -> tuple[str, str]:
        fn_name = fn.name
        py_fn_name = f"py_{self.module_name}_{fn_name}"

        # Parametre tiplerini çözümle
        param_types: List[str] = []
        parse_format_chars: List[str] = []
        parse_vars: List[str] = []
        call_args: List[str] = []

        for i, p in enumerate(fn.params):
            t_val = getattr(p.type_annot, "raw", p.type_annot) if p.type_annot else "double"
            t_str = str(t_val).strip().lower()
            var_name = f"arg_{p.name}"

            if t_str in ("int", "i32", "i64", "long"):
                param_types.append(f"int {var_name};")
                parse_format_chars.append("i")
                parse_vars.append(f"&{var_name}")
                call_args.append(var_name)
            elif t_str in ("float", "double", "f32", "f64"):
                param_types.append(f"double {var_name};")
                parse_format_chars.append("d")
                parse_vars.append(f"&{var_name}")
                call_args.append(var_name)
            elif t_str in ("str", "string"):
                param_types.append(f"const char* {var_name};")
                parse_format_chars.append("s")
                parse_vars.append(f"&{var_name}")
                call_args.append(var_name)
            elif t_str in ("bool", "boolean"):
                param_types.append(f"int {var_name};")
                parse_format_chars.append("p")
                parse_vars.append(f"&{var_name}")
                call_args.append(var_name)
            else:
                # Varsayılan double
                param_types.append(f"double {var_name};")
                parse_format_chars.append("d")
                parse_vars.append(f"&{var_name}")
                call_args.append(var_name)

        fmt_str = "".join(parse_format_chars)
        parse_args_str = ", ".join(parse_vars)

        wrapper_lines = [
            f"static PyObject* {py_fn_name}(PyObject* self, PyObject* args) {{",
        ]

        if param_types:
            for pt in param_types:
                wrapper_lines.append(f"    {pt}")
            wrapper_lines.append(f'    if (!PyArg_ParseTuple(args, "{fmt_str}", {parse_args_str})) {{')
            wrapper_lines.append("        return NULL;")
            wrapper_lines.append("    }")

        call_expr = f"{fn_name}({', '.join(call_args)})"
        ret_val = getattr(fn.return_type, "raw", fn.return_type) if fn.return_type else "double"
        ret_type = str(ret_val).strip().lower()


        if ret_type in ("int", "i32", "i64", "long"):
            wrapper_lines.append(f"    int result = {call_expr};")
            wrapper_lines.append("    return PyLong_FromLong((long)result);")
        elif ret_type in ("float", "double", "f32", "f64"):
            wrapper_lines.append(f"    double result = {call_expr};")
            wrapper_lines.append("    return PyFloat_FromDouble(result);")
        elif ret_type in ("str", "string"):
            wrapper_lines.append(f"    const char* result = {call_expr};")
            wrapper_lines.append("    return PyUnicode_FromString(result);")
        elif ret_type in ("bool", "boolean"):
            wrapper_lines.append(f"    int result = {call_expr};")
            wrapper_lines.append("    return PyBool_FromLong(result);")
        elif ret_type == "void":
            wrapper_lines.append(f"    {call_expr};")
            wrapper_lines.append("    Py_RETURN_NONE;")
        else:
            wrapper_lines.append(f"    double result = (double){call_expr};")
            wrapper_lines.append("    return PyFloat_FromDouble(result);")

        wrapper_lines.append("}")
        wrapper_lines.append("")

        table_entry = f'{{"{fn_name}", {py_fn_name}, METH_VARARGS, "Synapse compiled function: {fn_name}"}}'
        return "\n".join(wrapper_lines), table_entry
